<template>
  <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-3">
    <div class="w-full max-w-xl max-h-[88vh] overflow-hidden border border-slate-200 bg-white shadow-lg">
      <div class="flex items-center justify-between border-b border-slate-200 px-4 py-2.5">
        <div><h2 class="text-sm font-semibold text-slate-900">Edit payment plan</h2><p class="text-[10px] text-slate-500">Payment plan details</p></div>
        <button type="button" @click="close" class="h-7 w-7 border border-slate-200 text-xs text-slate-500">×</button>
      </div>
      <form v-else @submit.prevent="submit"><div class="grid gap-2 p-3 md:grid-cols-2 max-h-[calc(88vh-112px)] overflow-y-auto"><Field label="Payment type"><select v-model="form.payment_type" class="input"><option>down_payment</option><option>installment</option><option>final_payment</option><option>other</option></select></Field><Field label="Frequency"><select v-model="form.frequency" class="input"><option>monthly</option><option>weekly</option><option>quarterly</option><option>yearly</option><option>one_time</option></select></Field><Field label="Amount"><input v-model="form.amount" class="input"/></Field><Field label="Due date"><input v-model="form.due_date" type="date" class="input"/></Field><Field label="Installment number"><input v-model.number="form.installment_number" type="number" class="input"/></Field><Field label="Total installments"><input v-model.number="form.total_installments" type="number" class="input"/></Field><Field label="Application" required><select v-model.number="form.application" class="input" required><option :value="0" disabled>Select application</option><option v-for="item in applications" :key="item.id" :value="item.id">#{{ item.id }} — {{ applicationLabel(item) }}</option></select></Field><Field label="Completed"><input v-model="form.is_completed" type="checkbox" class="h-4 w-4"/></Field><Field label="Description"><textarea v-model="form.description" class="input min-h-24"></textarea></Field></div><div v-if="error" class="mx-3 mb-2 flex h-7 items-center overflow-hidden border border-red-200 bg-red-50 px-2 text-[10px] text-red-700">{{error}}</div><div class="flex justify-end gap-2 border-t border-slate-200 bg-slate-50 px-3 py-2"><button type="button" @click="close" class="border px-3 py-1.5">Cancel</button><button :disabled="saving" class="bg-primary px-3 py-1.5 text-white text-xs">{{saving?'Saving…':'Save changes'}}</button></div></form>
    </div>
  </div>
</template><script>import OffplanField from "../offplan property/OffplanField.vue";const blank={payment_type:"down_payment",frequency:"monthly",amount:"",due_date:"",installment_number:0,total_installments:0,description:"",is_completed:true,application:0};export default{name:"EditOffplanPaymentPlan",components:{Field:OffplanField},props:{open:Boolean,id:[String,Number]},data(){return{form:{...blank},applications:[],loadingData:false,saving:false,error:""}},watch:{open(v){if(v){this.loadApplications();this.load()}}},methods:{async loadApplications(){try{const r=await this.$apiGet("/get_offplan_applications");const d=r?.data?.data||r?.data||r?.applications||r;const rows=Array.isArray(d)?d:(d?.results||[]);this.applications=rows}catch(e){this.error="Unable to load applications."}},applicationLabel(item){return item?.customer?.name||item?.customer?.full_name||item?.customer||item?.offplan_property?.name||item?.offplan_property||"Application"},close(){if(!this.saving)this.$emit("close")},async load(){this.loadingData=true;try{const r=await this.$apiGetById("/get_offplan_payment_plan",this.id);this.form={...blank,...(r?.data?.data||r?.data||r?.payment_plan||r)}}catch(e){this.error=e?.message||"Unable to load plan."}finally{this.loadingData=false}},async submit(){this.saving=true;try{await this.$apiPatch("/update_offplan_payment_plan",this.id,{...this.form,installment_number:Number(this.form.installment_number),total_installments:Number(this.form.total_installments),application:Number(this.form.application)});this.$emit("saved");this.close()}catch(e){this.error=e?.message||"Unable to update plan."}finally{this.saving=false}}}};</script><style scoped>.input{width:100%;border:1px solid #cbd5e1;padding:.625rem .75rem;outline:none}</style>