<template>
  <div class="min-h-full bg-slate-50 p-4 md:p-6 lg:p-8">
    <div class="mx-auto max-w-6xl">
      <div v-if="loading" class="rounded-2xl border border-slate-200 bg-white p-12 text-center text-slate-500"><i class="fas fa-spinner fa-spin mr-2"></i>Loading property…</div>
      <template v-else>
        <div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div><div class="mb-2 flex items-center gap-2 text-sm text-slate-500"><router-link :to="{name:'OffplanProperty-view'}" class="hover:text-blue-600">Offplan Properties</router-link><i class="fas fa-chevron-right text-[10px]"></i><span>Property detail</span></div><div class="flex flex-wrap items-center gap-3"><h1 class="text-2xl font-black tracking-tight text-slate-900">Offplan Property</h1><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{{display(form.project_status)}}</span></div><p class="mt-1 text-sm text-slate-500">{{form.developer || 'Developer not specified'}} · {{form.property_type || 'Property'}}</p></div>
          <div class="flex gap-2"><router-link :to="{name:'OffplanProperty-edit',params:{id}}" class="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white hover:bg-blue-700"><i class="fas fa-pen mr-2"></i>Edit</router-link><router-link :to="{name:'OffplanProperty-view'}" class="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700">Back</router-link></div>
        </div>
        <div v-if="error" class="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{error}}</div>
        <div class="grid gap-6 lg:grid-cols-3">
          <div class="space-y-6 lg:col-span-2">
            <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-6 py-5"><h2 class="font-bold text-slate-900">Property overview</h2></div><div class="grid grid-cols-2 gap-px bg-slate-100 sm:grid-cols-4"><Stat label="Price" :value="form.price || '—'" /><Stat label="Bedrooms" :value="form.bedrooms || '—'" /><Stat label="Bathrooms" :value="form.bathrooms || '—'" /><Stat label="Area / size" :value="form.area_or_size || '—'" /></div><div class="grid gap-4 p-6 sm:grid-cols-2"><Info label="Completion status" :value="display(form.completion_status)" /><Info label="Sale type" :value="display(form.sale_type)" /><Info label="Project completion" :value="display(form.project_completion)" /><Info label="Pre-handover payment" :value="display(form.pre_handover_payment)" /><Info label="Project status" :value="display(form.project_status)" /><Info label="Developer" :value="form.developer || '—'" /></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-6 py-5"><h2 class="font-bold text-slate-900">Amenities & features</h2></div><div class="grid gap-3 p-6 sm:grid-cols-2"><div v-for="item in amenityOptions" :key="item.key" class="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span class="flex h-8 w-8 items-center justify-center rounded-lg" :class="form[item.key] ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-50 text-slate-400'"><i :class="form[item.key] ? 'fas fa-check' : 'fas fa-minus'"></i></span><span class="text-sm font-medium text-slate-700">{{item.label}}</span></div></div></section>
          </div>
          <aside class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="mb-4 font-bold text-slate-900">Relationships</h2><div class="space-y-4"><Info label="Property zone" :value="form.property_zone ?? '—'" /><Info label="Owner" :value="form.owner ?? '—'" /><Info label="Manager" :value="form.manager ?? '—'" /></div></section><section class="rounded-2xl border border-blue-100 bg-blue-50/60 p-6"><div class="flex items-start gap-3"><i class="fas fa-circle-info mt-0.5 text-blue-600"></i><p class="text-sm leading-6 text-blue-900">This record is connected to the authenticated property-management workspace and uses the offplan property API endpoints.</p></div></section></aside>
        </div>
      </template>
    </div>
  </div>
</template>
<script>
export default {name:"OffplanPropertyDetail",props:{id:[String,Number]},components:{Info:{props:["label","value"],template:'<div><p class="text-[11px] font-bold uppercase tracking-wide text-slate-400">{{label}}</p><p class="mt-1 text-sm font-semibold text-slate-800 break-words">{{value}}</p></div>'},Stat:{props:["label","value"],template:'<div class="bg-white p-5"><p class="text-[11px] font-bold uppercase tracking-wide text-slate-400">{{label}}</p><p class="mt-2 text-lg font-black text-slate-900 break-words">{{value}}</p></div>'}},data(){return{form:{},loading:true,error:"",amenityOptions:[{key:"is_furnished",label:"Furnished"},{key:"has_maids_room",label:"Maid’s room"},{key:"has_study",label:"Study"},{key:"has_central_or_ac_and_heating",label:"Central A/C & heating"},{key:"has_balcony",label:"Balcony"},{key:"has_private_garden",label:"Private garden"},{key:"has_private_pool",label:"Private pool"},{key:"has_private_gym",label:"Private gym"},{key:"has_private_jacuzzi",label:"Private jacuzzi"},{key:"has_shared_pool",label:"Shared pool"},{key:"has_shared_spa",label:"Shared spa"}]}},async mounted(){try{const res=await this.$apiGetById("/get_offplan_property",this.id);this.form=res?.data?.data||res?.data||res?.property||res||{}}catch(e){this.error=e?.message||"Unable to load property."}finally{this.loading=false}},methods:{display(v){if(v===null||v===undefined||v==="")return"—";return String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}}};
</script>
