<template>
  <div class="min-h-full bg-slate-50 p-4 md:p-6 lg:p-8">
    <div class="mx-auto max-w-7xl">
      <div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><div class="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-blue-600"><i class="fas fa-building"></i> Offplan portfolio</div><h1 class="text-2xl font-black tracking-tight text-slate-900">Offplan Properties</h1><p class="mt-1 text-sm text-slate-500">Manage residential projects, pricing, completion progress and amenities.</p></div>
        <router-link :to="{name:'OffplanProperty-add'}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-blue-700"><i class="fas fa-plus"></i> Add offplan property</router-link>
      </div>
      <div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Total properties</p><p class="mt-2 text-2xl font-black text-slate-900">{{filteredProperties.length}}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Under construction</p><p class="mt-2 text-2xl font-black text-slate-900">{{underConstruction}}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Ready</p><p class="mt-2 text-2xl font-black text-slate-900">{{readyCount}}</p></div></div>
      <div class="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 md:flex-row"><div class="relative flex-1"><i class="fas fa-search absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input v-model="search" class="w-full rounded-xl border border-slate-200 py-3 pl-11 pr-4 text-sm outline-none focus:border-blue-300" placeholder="Search developer, property type, status…" /></div><button @click="loadProperties" class="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"><i class="fas fa-rotate mr-2"></i>Refresh</button></div></div>
      <div v-if="loading" class="rounded-2xl border border-slate-200 bg-white p-12 text-center text-slate-500"><i class="fas fa-spinner fa-spin mr-2"></i>Loading offplan properties…</div>
      <div v-else-if="error" class="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{{error}} <button @click="loadProperties" class="ml-2 font-bold underline">Retry</button></div>
      <div v-else-if="filteredProperties.length === 0" class="rounded-2xl border border-dashed border-slate-300 bg-white p-14 text-center"><div class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><i class="fas fa-building text-xl"></i></div><h2 class="font-bold text-slate-900">No offplan properties found</h2><p class="mt-1 text-sm text-slate-500">Create your first property or adjust your search.</p></div>
      <div v-else class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        <article v-for="item in filteredProperties" :key="item.id" class="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">
          <div class="flex items-start justify-between bg-gradient-to-br from-slate-900 to-slate-700 p-5 text-white"><div><p class="text-xs font-semibold uppercase tracking-wider text-slate-300">{{display(item.property_type)}}</p><h2 class="mt-1 text-lg font-black">{{item.developer || 'Offplan development'}}</h2></div><span class="rounded-full bg-white/10 px-2.5 py-1 text-[11px] font-bold">{{display(item.project_status)}}</span></div>
          <div class="p-5"><div class="mb-5 grid grid-cols-3 gap-3"><div><p class="text-[10px] font-bold uppercase text-slate-400">Price</p><p class="mt-1 truncate text-sm font-black text-slate-900">{{item.price || '—'}}</p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Beds</p><p class="mt-1 text-sm font-bold text-slate-800">{{item.bedrooms || '—'}}</p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Area</p><p class="mt-1 truncate text-sm font-bold text-slate-800">{{item.area_or_size || '—'}}</p></div></div><div class="mb-5 flex flex-wrap gap-2"><span v-for="tag in tags(item)" :key="tag" class="rounded-lg bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600">{{tag}}</span></div><div class="flex gap-2 border-t border-slate-100 pt-4"><router-link :to="{name:'OffplanProperty-detail',params:{id:item.id}}" class="flex-1 rounded-xl bg-slate-900 px-3 py-2.5 text-center text-xs font-bold text-white hover:bg-blue-700">View details</router-link><router-link :to="{name:'OffplanProperty-edit',params:{id:item.id}}" class="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700 hover:bg-slate-50" title="Edit"><i class="fas fa-pen"></i></router-link></div></div>
        </article>
      </div>
    </div>
  </div>
</template>
<script>
export default {name:"ViewOffplanProperty",data(){return{properties:[],search:"",loading:true,error:""}},computed:{filteredProperties(){const q=this.search.trim().toLowerCase();if(!q)return this.properties;return this.properties.filter(p=>[p.developer,p.property_type,p.project_status,p.completion_status,p.sale_type].some(v=>String(v??"").toLowerCase().includes(q)))},underConstruction(){return this.filteredProperties.filter(p=>p.project_status==="under_construction").length},readyCount(){return this.filteredProperties.filter(p=>p.completion_status==="ready").length}},async mounted(){await this.loadProperties();if(this.$route.query.created){this.$router.replace({name:"OffplanProperty-view"})}},methods:{async loadProperties(){this.loading=true;this.error="";try{const res=await this.$apiGet("/get_offplan_properties");const data=res?.data?.data||res?.data||res?.properties||res;this.properties=Array.isArray(data)?data:(data?.results||[])}catch(e){this.error=e?.message||"Unable to load offplan properties."}finally{this.loading=false}},display(v){if(v===null||v===undefined||v==="")return"—";return String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())},tags(item){return [item.completion_status&&this.display(item.completion_status),item.project_completion&&this.display(item.project_completion),item.sale_type&&this.display(item.sale_type)].filter(Boolean)}}};
</script>
