<template>
<div class="min-h-screen bg-slate-50 p-5 text-sm text-slate-800"><div class="mx-auto max-w-[1600px] space-y-5">
<header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-primary">Alpha PMS · Development Report</div><h1 class="text-2xl font-black tracking-tight text-slate-900">Off-plan Properties Report</h1><p class="mt-1 text-xs text-slate-500">Project progress, inventory, applications and collections · sample data only</p></div><button @click="exportCsv" class="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white"><i class="fas fa-download mr-2"></i>Export</button></header>
<div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="c in cards" :key="c.label" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{c.label}}</div><div class="mt-2 text-2xl font-black text-slate-900">{{c.value}}</div><div class="mt-1 text-[11px] text-slate-500">{{c.note}}</div></div></div>
<section class="grid gap-5 lg:grid-cols-2"><div v-for="p in projects" :key="p.id" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-black">{{p.name}}</h2><p class="mt-1 text-xs text-slate-400">{{p.location}} · {{p.developer}}</p></div><span class="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-black text-primary">{{p.progress}}% built</span></div><div class="mt-5 grid grid-cols-3 gap-3 text-center"><div class="rounded-lg bg-slate-50 p-3"><div class="text-lg font-black">{{p.units}}</div><div class="text-[10px] uppercase text-slate-400">Units</div></div><div class="rounded-lg bg-slate-50 p-3"><div class="text-lg font-black">{{p.sold}}</div><div class="text-[10px] uppercase text-slate-400">Sold</div></div><div class="rounded-lg bg-slate-50 p-3"><div class="text-lg font-black">{{p.available}}</div><div class="text-[10px] uppercase text-slate-400">Available</div></div></div><div class="mt-5"><div class="mb-1 flex justify-between text-xs font-bold"><span>Construction progress</span><span>{{p.progress}}%</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary" :style="{width:p.progress+'%'}"></div></div></div><div class="mt-4 flex justify-between text-xs"><span class="text-slate-500">Applications <b class="text-slate-800">{{p.applications}}</b></span><span class="font-black">{{p.collected.toLocaleString()}} ETB collected</span></div></div></section>
<section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="font-black">Off-plan Inventory</h2></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Project</th><th class="px-4 py-3">Unit Type</th><th class="px-4 py-3">Price</th><th class="px-4 py-3">Payment Plan</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="u in inventory" :key="u.id" class="hover:bg-slate-50"><td class="px-4 py-3 font-bold">{{u.project}}</td><td class="px-4 py-3 text-xs">{{u.type}}</td><td class="px-4 py-3 text-xs font-bold">{{u.price.toLocaleString()}} ETB</td><td class="px-4 py-3 text-xs">{{u.plan}}</td><td class="px-4 py-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{{u.status}}</span></td></tr></tbody></table></div></section>
</div></div></template>
<script>
export default{name:"OffplanPropertiesReport",data(){return{projects:[
{id:1,name:"Luna Residences",location:"Bole Arabsa",developer:"Luna Developments",units:120,sold:74,available:46,progress:68,applications:91,collected:18650000},
{id:2,name:"Nile View Towers",location:"Sarbet",developer:"Nile View Development",units:84,sold:51,available:33,progress:44,applications:63,collected:12780000}],inventory:[
{id:1,project:"Luna Residences",type:"2 Bedroom",price:4200000,plan:"30 / 40 / 30",status:"Available"},
{id:2,project:"Luna Residences",type:"3 Bedroom",price:5850000,plan:"20 / 30 / 50",status:"Reserved"},
{id:3,project:"Nile View Towers",type:"1 Bedroom",price:3100000,plan:"25 / 25 / 50",status:"Available"},
{id:4,project:"Nile View Towers",type:"2 Bedroom",price:4550000,plan:"20 / 40 / 40",status:"Sold"}]}},computed:{cards(){return[{label:"Active projects",value:this.projects.length,note:"Sample developments"},{label:"Total units",value:this.projects.reduce((a,p)=>a+p.units,0),note:"Project inventory"},{label:"Units sold",value:this.projects.reduce((a,p)=>a+p.sold,0),note:"Across projects"},{label:"Collected",value:"31.43M ETB",note:"Sample collections"}]}},methods:{exportCsv(){const rows=[["Project","Unit Type","Price","Payment Plan","Status"],...this.inventory.map(u=>[u.project,u.type,u.price,u.plan,u.status])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"}));a.download="alpha-pms-offplan-report.csv";a.click();URL.revokeObjectURL(a.href)}}}
</script>