<template>
<div class="min-h-screen bg-slate-50 p-5 text-sm text-slate-800"><div class="mx-auto max-w-[1600px] space-y-5">
<header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-primary">Alpha PMS · Portfolio Report</div><h1 class="text-2xl font-black tracking-tight text-slate-900">Properties Report</h1><p class="mt-1 text-xs text-slate-500">Occupancy, status and rental performance · sample data only</p></div><button @click="exportCsv" class="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white"><i class="fas fa-download mr-2"></i>Export</button></header>
<div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="c in cards" :key="c.label" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{c.label}}</div><div class="mt-2 text-2xl font-black text-slate-900">{{c.value}}</div><div class="mt-1 text-[11px] text-slate-500">{{c.note}}</div></div></div>
<section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 class="font-black">Property Portfolio</h2><p class="mt-1 text-xs text-slate-400">Uses the same property, zone, owner, type and status vocabulary as the PMS</p></div><select v-model="status" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold"><option>All</option><option>Available</option><option>For Rent</option><option>For Sale</option><option>Rented</option><option>Under Maintenance</option></select></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Property</th><th class="px-4 py-3">Owner / Zone</th><th class="px-4 py-3">Type</th><th class="px-4 py-3">Units</th><th class="px-4 py-3">Occupancy</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Rent / Mo.</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="p in filtered" :key="p.id" class="hover:bg-slate-50"><td class="px-4 py-3 font-bold">{{p.name}}</td><td class="px-4 py-3"><div class="text-xs font-semibold">{{p.owner}}</div><div class="text-[11px] text-slate-400">{{p.zone}}</div></td><td class="px-4 py-3 text-xs">{{p.type}}</td><td class="px-4 py-3 text-xs font-bold">{{p.units}}</td><td class="px-4 py-3"><div class="flex items-center gap-2"><div class="h-1.5 w-16 rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary" :style="{width:p.occupancy+'%'}"></div></div><span class="text-xs font-bold">{{p.occupancy}}%</span></div></td><td class="px-4 py-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{{p.status}}</span></td><td class="px-4 py-3 text-xs font-black">{{p.rent.toLocaleString()}} ETB</td></tr></tbody></table></div></section>
</div></div></template>
<script>
export default{name:"PropertiesReport",data(){return{status:"All",properties:[
{id:1,name:"Bole Heights",owner:"Amanuel Tesfaye",zone:"Bole",type:"Apartment",units:24,occupancy:92,status:"Rented",rent:480000},
{id:2,name:"Summit Court",owner:"Hana Worku",zone:"Summit",type:"Mixed Use",units:18,occupancy:78,status:"For Rent",rent:315000},
{id:3,name:"Kazanchis Plaza",owner:"Alpha Holdings",zone:"Kazanchis",type:"Office",units:30,occupancy:87,status:"For Sale",rent:620000},
{id:4,name:"Lebu Garden Villas",owner:"Marta Alemu",zone:"Lebu",type:"Villa",units:10,occupancy:100,status:"Rented",rent:260000},
{id:5,name:"CMC Residences",owner:"Blue Nile Estates",zone:"CMC",type:"Apartment",units:36,occupancy:69,status:"Under Maintenance",rent:540000}]}},computed:{filtered(){return this.status==="All"?this.properties:this.properties.filter(p=>p.status===this.status)},cards(){const units=this.properties.reduce((a,p)=>a+p.units,0);const occ=Math.round(this.properties.reduce((a,p)=>a+p.units*p.occupancy,0)/units);return[{label:"Properties",value:this.properties.length,note:"Sample portfolio"},{label:"Units",value:units,note:"Across all properties"},{label:"Occupancy",value:occ+"%",note:"Weighted by units"},{label:"Monthly rent",value:"2.22M ETB",note:"Sample gross rent"}]}},methods:{exportCsv(){const rows=[["Property","Owner","Zone","Type","Units","Occupancy","Status","Monthly Rent"],...this.filtered.map(p=>[p.name,p.owner,p.zone,p.type,p.units,p.occupancy,p.status,p.rent])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"}));a.download="alpha-pms-properties-report.csv";a.click();URL.revokeObjectURL(a.href)}}}
</script>