<template>
<div class="min-h-screen bg-slate-50 p-5 text-sm text-slate-800"><div class="mx-auto max-w-[1600px] space-y-5">
<header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-primary">Alpha PMS · Executive Report</div><h1 class="text-2xl font-black tracking-tight text-slate-900">Revenues Report</h1><p class="mt-1 text-xs text-slate-500">Rent, sales, subscriptions, workspace and off-plan streams · sample data only</p></div><button @click="exportCsv" class="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white"><i class="fas fa-download mr-2"></i>Export</button></header>
<div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="c in cards" :key="c.label" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{c.label}}</div><div class="mt-2 text-2xl font-black text-slate-900">{{c.value}}</div><div class="mt-1 text-[11px] text-slate-500">{{c.note}}</div></div></div>
<section class="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Monthly Revenue Trend</h2><p class="mt-1 text-xs text-slate-400">Illustrative six-month sample</p><div class="mt-8 flex h-56 items-end gap-3 border-b border-slate-100 pb-1"><div v-for="m in months" :key="m.label" class="flex h-full flex-1 flex-col justify-end gap-2"><div class="rounded-t-lg bg-primary/80" :style="{height:(m.total/maxRevenue*100)+'%'}"></div><span class="text-center text-[10px] font-bold text-slate-400">{{m.label}}</span></div></div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Revenue Mix</h2><div class="mt-5 space-y-4"><div v-for="r in streams" :key="r.name"><div class="mb-1 flex justify-between text-xs font-bold"><span>{{r.name}}</span><span>{{r.value.toLocaleString()}}</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary" :style="{width:r.pct+'%'}"></div></div></div></div></div></section>
<section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="font-black">Revenue Ledger</h2></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Period</th><th class="px-4 py-3">Rent</th><th class="px-4 py-3">Sales</th><th class="px-4 py-3">Subscriptions</th><th class="px-4 py-3">Workspace</th><th class="px-4 py-3">Off-plan</th><th class="px-4 py-3">Total</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="m in months" :key="m.label" class="hover:bg-slate-50"><td class="px-4 py-3 font-bold">{{m.label}}</td><td class="px-4 py-3 text-xs">{{m.rent.toLocaleString()}}</td><td class="px-4 py-3 text-xs">{{m.sales.toLocaleString()}}</td><td class="px-4 py-3 text-xs">{{m.subscription.toLocaleString()}}</td><td class="px-4 py-3 text-xs">{{m.workspace.toLocaleString()}}</td><td class="px-4 py-3 text-xs">{{m.offplan.toLocaleString()}}</td><td class="px-4 py-3 text-xs font-black">{{m.total.toLocaleString()}} ETB</td></tr></tbody></table></div></section>
</div></div></template>
<script>
export default{name:"RevenuesReport",data(){return{months:[
{label:"May",rent:680000,sales:420000,subscription:59600,workspace:126000,offplan:740000,total:2025600},
{label:"Jun",rent:710000,sales:620000,subscription:59600,workspace:139000,offplan:920000,total:2448600},
{label:"Jul",rent:735000,sales:380000,subscription:59600,workspace:148000,offplan:1150000,total:2472600},
{label:"Aug",rent:760000,sales:810000,subscription:59600,workspace:157000,offplan:980000,total:2766600},
{label:"Sep",rent:785000,sales:540000,subscription:59600,workspace:166000,offplan:1260000,total:2810600},
{label:"Oct",rent:812000,sales:690000,subscription:59600,workspace:174000,offplan:1340000,total:3085600}] }},computed:{maxRevenue(){return Math.max(...this.months.map(m=>m.total))},streams(){const keys=[["Rent","rent"],["Sales","sales"],["Subscriptions","subscription"],["Workspace","workspace"],["Off-plan","offplan"]];const total=this.months.reduce((a,m)=>a+m.total,0);return keys.map(([name,key])=>{const value=this.months.reduce((a,m)=>a+m[key],0);return{name,key,value,pct:Math.round(value/total*100)}})},cards(){const total=this.months.reduce((a,m)=>a+m.total,0);return[{label:"6-mo. revenue",value:(total/1000000).toFixed(2)+"M ETB",note:"Illustrative sample"},{label:"Latest month",value:"3.09M ETB",note:"+9.9% vs Sep"},{label:"Rent share",value:this.streams.find(s=>s.key==="rent").pct+"%",note:"Recurring core"},{label:"Revenue streams",value:5,note:"Across PMS modules"}]}},methods:{exportCsv(){const rows=[["Period","Rent","Sales","Subscriptions","Workspace","Off-plan","Total"],...this.months.map(m=>[m.label,m.rent,m.sales,m.subscription,m.workspace,m.offplan,m.total])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"}));a.download="alpha-pms-revenue-report.csv";a.click();URL.revokeObjectURL(a.href)}}}
</script>