<template>
<div class="min-h-screen bg-slate-50 p-5 text-sm text-slate-800"><div class="mx-auto max-w-[1600px] space-y-5">
<header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-primary">Alpha PMS · Executive Report</div></div><button @click="exportCsv" class="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white"><i class="fas fa-download mr-2"></i>Export</button></header>
<div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="c in cards" :key="c.label" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{c.label}}</div><div class="mt-2 text-2xl font-black text-slate-900">{{c.value}}</div><div class="mt-1 text-[11px] font-semibold text-slate-500">{{c.note}}</div></div></div>
<section class="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Plan Mix</h2><p class="mt-1 text-xs text-slate-400">Current sample account distribution</p><div class="mt-6 space-y-5"><div v-for="p in plans" :key="p.name"><div class="mb-1 flex justify-between text-xs font-bold"><span>{{p.name}}</span><span>{{p.subscribers}} subscribers</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary" :style="{width:p.share+'%'}"></div></div></div></div></div>
<div class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="font-black">Subscription Ledger</h2><p class="mt-1 text-xs text-slate-400">Aligned with plans and subscription payment concepts in the PMS</p></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Account</th><th class="px-4 py-3">Plan</th><th class="px-4 py-3">Billing</th><th class="px-4 py-3">Renewal</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="s in subscriptions" :key="s.id" class="hover:bg-slate-50"><td class="px-4 py-3 font-bold">{{s.account}}</td><td class="px-4 py-3 text-xs">{{s.plan}}</td><td class="px-4 py-3 text-xs font-semibold">{{s.amount.toLocaleString()}} ETB</td><td class="px-4 py-3 text-xs text-slate-500">{{s.renewal}}</td><td class="px-4 py-3"><span :class="s.status==='Active'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'" class="rounded-full px-2 py-1 text-[10px] font-bold">{{s.status}}</span></td></tr></tbody></table></div></div></section>
</div></div></template>
<script>
export default{name:"SubscriptionReport",data(){return{subscriptions:[
{id:1,account:"Alpha Realty Group",plan:"Enterprise",amount:18500,renewal:"2026-11-15",status:"Active"},
{id:2,account:"Horizon Properties",plan:"Professional",amount:9200,renewal:"2026-10-28",status:"Active"},
{id:3,account:"Blue Nile Estates",plan:"Professional",amount:9200,renewal:"2026-10-19",status:"Active"},
{id:4,account:"Meklit Workspace",plan:"Starter",amount:4200,renewal:"2026-10-09",status:"Pending"},
{id:5,account:"Sunrise Holdings",plan:"Enterprise",amount:18500,renewal:"2026-12-02",status:"Active"}],plans:[{name:"Enterprise",subscribers:2,share:40},{name:"Professional",subscribers:2,share:40},{name:"Starter",subscribers:1,share:20}]}},computed:{cards(){return[{label:"Active subscriptions",value:this.subscriptions.filter(s=>s.status==="Active").length,note:"Recurring accounts"},{label:"Sample MRR",value:"59,600 ETB",note:"Before adjustments"},{label:"Avg. plan value",value:"11,920 ETB",note:"Per account / cycle"},{label:"Renewals due",value:2,note:"Within 30 days"}]}},methods:{exportCsv(){const rows=[["Account","Plan","Amount","Renewal","Status"],...this.subscriptions.map(s=>[s.account,s.plan,s.amount,s.renewal,s.status])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"}));a.download="alpha-pms-subscription-report.csv";a.click();URL.revokeObjectURL(a.href)}}}
</script>