<template>
<div class="min-h-screen bg-slate-50 p-5 text-sm text-slate-800"><div class="mx-auto max-w-[1600px] space-y-5">
<header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-primary">Alpha PMS · Workspace Report</div><h1 class="text-2xl font-black tracking-tight text-slate-900">Workspace Report</h1><p class="mt-1 text-xs text-slate-500">Co-work spaces, capacity, rentals and payments · sample data only</p></div><button @click="exportCsv" class="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white"><i class="fas fa-download mr-2"></i>Export</button></header>
<div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="c in cards" :key="c.label" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{c.label}}</div><div class="mt-2 text-2xl font-black text-slate-900">{{c.value}}</div><div class="mt-1 text-[11px] text-slate-500">{{c.note}}</div></div></div>
<section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="font-black">Workspace Portfolio</h2><p class="mt-1 text-xs text-slate-400">Aligned with spaces, workspace rentals and workspace payments</p></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Space</th><th class="px-4 py-3">Location</th><th class="px-4 py-3">Capacity</th><th class="px-4 py-3">Occupied</th><th class="px-4 py-3">Occupancy</th><th class="px-4 py-3">Active Rentals</th><th class="px-4 py-3">Revenue / Mo.</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="w in workspaces" :key="w.id" class="hover:bg-slate-50"><td class="px-4 py-3 font-bold">{{w.name}}</td><td class="px-4 py-3 text-xs text-slate-500">{{w.location}}</td><td class="px-4 py-3 text-xs">{{w.capacity}}</td><td class="px-4 py-3 text-xs font-bold">{{w.occupied}}</td><td class="px-4 py-3"><div class="flex items-center gap-2"><div class="h-1.5 w-16 rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary" :style="{width:w.occupancy+'%'}"></div></div><span class="text-xs font-bold">{{w.occupancy}}%</span></div></td><td class="px-4 py-3 text-xs">{{w.rentals}}</td><td class="px-4 py-3 text-xs font-black">{{w.revenue.toLocaleString()}} ETB</td></tr></tbody></table></div></section>
<section class="grid gap-5 lg:grid-cols-2"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Workspace Revenue</h2><div class="mt-5 space-y-4"><div v-for="w in workspaces" :key="w.id"><div class="mb-1 flex justify-between text-xs font-bold"><span>{{w.name}}</span><span>{{w.revenue.toLocaleString()}} ETB</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary" :style="{width:(w.revenue/maxRevenue*100)+'%'}"></div></div></div></div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Sample Rental Activity</h2><div class="mt-4 divide-y divide-slate-100"><div v-for="r in rentals" :key="r.id" class="flex items-center justify-between py-3"><div><p class="text-xs font-bold">{{r.guest}}</p><p class="text-[11px] text-slate-400">{{r.space}} · {{r.cycle}}</p></div><span :class="r.status==='Paid'?'text-emerald-600 bg-emerald-50':'text-amber-700 bg-amber-50'" class="rounded-full px-2 py-1 text-[10px] font-bold">{{r.status}}</span></div></div></div></section>
</div></div></template>
<script>
export default{name:"WorkspaceReport",data(){return{workspaces:[
{id:1,name:"Alpha Hub Bole",location:"Bole",capacity:48,occupied:41,occupancy:85,rentals:27,revenue:92000},
{id:2,name:"Alpha Hub Kazanchis",location:"Kazanchis",capacity:64,occupied:52,occupancy:81,rentals:34,revenue:118000},
{id:3,name:"Alpha Hub CMC",location:"CMC",capacity:36,occupied:25,occupancy:69,rentals:18,revenue:64000}],rentals:[
{id:1,guest:"Liya Consulting",space:"Alpha Hub Bole",cycle:"Monthly",status:"Paid"},
{id:2,guest:"Mekdes Studio",space:"Alpha Hub Kazanchis",cycle:"Monthly",status:"Paid"},
{id:3,guest:"Kora Design",space:"Alpha Hub CMC",cycle:"Weekly",status:"Pending"},
{id:4,guest:"Nile Tech",space:"Alpha Hub Kazanchis",cycle:"Monthly",status:"Paid"}]}},computed:{maxRevenue(){return Math.max(...this.workspaces.map(w=>w.revenue))},cards(){const cap=this.workspaces.reduce((a,w)=>a+w.capacity,0);const occ=this.workspaces.reduce((a,w)=>a+w.occupied,0);return[{label:"Workspace locations",value:this.workspaces.length,note:"Sample active spaces"},{label:"Total capacity",value:cap,note:"Desks / seats"},{label:"Occupancy",value:Math.round(occ/cap*100)+"%",note:"Weighted occupancy"},{label:"Monthly revenue",value:this.workspaces.reduce((a,w)=>a+w.revenue,0).toLocaleString()+" ETB",note:"Sample workspace income"}]}},methods:{exportCsv(){const rows=[["Space","Location","Capacity","Occupied","Occupancy","Active Rentals","Revenue"],...this.workspaces.map(w=>[w.name,w.location,w.capacity,w.occupied,w.occupancy,w.rentals,w.revenue])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"}));a.download="alpha-pms-workspace-report.csv";a.click();URL.revokeObjectURL(a.href)}}}
</script>