services:
  pms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpha-pms
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      TZ: Africa/Addis_Ababa
