name: alpha-pms

services:
  alpha_pms_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: alpha-pms:latest
    container_name: alpha-pms-frontend
    restart: unless-stopped

    expose:
      - "80"

    networks:
      - proxy-network


    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  proxy-network:
    external: true