<template>
  <div class="min-h-full bg-background p-4 md:p-6 lg:p-8"><div class="mx-auto max-w-7xl">
    <div class="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-primary">Offplan projects</p><h1 class="mt-1 text-2xl font-black text-slate-900">Offplan Milestones</h1><p class="mt-1 text-sm text-slate-500">Track project delivery dates and completion progress.</p></div><button @click="addOpen=true" class="border border-primary bg-primary px-5 py-2.5 text-sm font-bold text-white"><i class="fas fa-plus mr-2"></i>New milestone</button></div>
    <div class="mb-5 grid gap-3 sm:grid-cols-3"><div class="border border-slate-200 bg-white px-5 py-4"><p class="label">Total milestones</p><p class="big">{{filtered.length}}</p></div><div class="border border-slate-200 bg-white px-5 py-4"><p class="label">Planned</p><p class="big text-primary">{{plannedCount}}</p></div><div class="border border-slate-200 bg-white px-5 py-4"><p class="label">Completed</p><p class="big">{{completedCount}}</p></div></div>
    <div class="mb-4 flex gap-3 border border-slate-200 bg-white p-4"><input v-model="search" class="w-full border border-slate-200 py-2.5 px-3 text-sm outline-none focus:border-primary" placeholder="Search milestones, property or status"/><button @click="load" class="border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i class="fas fa-sync-alt mr-2"></i>Refresh</button></div>
    <div v-if="error" class="mb-4 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{error}}</div>
    <div class="overflow-hidden border border-slate-200 bg-white"><div v-if="loading" class="p-12 text-center text-sm text-slate-500"><i class="fas fa-spinner fa-spin mr-2"></i>Loading milestones…</div><div v-else-if="!filtered.length" class="p-12 text-center text-sm text-slate-500">No milestones found.</div><div v-else class="overflow-x-auto"><table class="min-w-full text-left"><thead class="border-b border-slate-200 bg-slate-50"><tr class="text-[11px] font-bold uppercase tracking-wider text-slate-500"><th class="px-5 py-3">Milestone</th><th class="px-5 py-3">Property</th><th class="px-5 py-3">Planned</th><th class="px-5 py-3">Actual</th><th class="px-5 py-3">Completion</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="item in filtered" :key="item.id" class="hover:bg-slate-50"><td class="px-5 py-4"><span class="font-bold text-slate-900">{{item.name||("#"+item.id)}}</span><p class="mt-0.5 text-xs text-slate-500">{{item.description||"No description"}}</p></td><td class="px-5 py-4 text-sm text-slate-700">{{relationLabel(item.offplan_property)}}</td><td class="px-5 py-4 text-sm">{{item.planned_date||"—"}}</td><td class="px-5 py-4 text-sm">{{item.actual_date||"—"}}</td><td class="px-5 py-4 text-sm font-bold">{{item.completion_percentage||"—"}}</td><td class="px-5 py-4"><span class="border border-primary/20 bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{{display(item.status)}}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><router-link :to="{name:'OffplanMilestone-detail',params:{id:item.id}}" class="border border-slate-200 px-3 py-2 text-xs font-semibold hover:border-primary hover:text-primary">View</router-link><button @click="openEdit(item.id)" class="border border-primary/20 px-3 py-2 text-xs font-semibold text-primary">Edit</button></div></td></tr></tbody></table></div></div>
    <AddOffplanMilestone :open="addOpen" @close="addOpen=false" @saved="load"/><EditOffplanMilestone :open="editOpen" :id="selectedId" @close="editOpen=false" @saved="load"/>
  </div></div>
</template>
<script>
import AddOffplanMilestone from "./AddOffplanMilestone.vue"; import EditOffplanMilestone from "./EditOffplanMilestone.vue";
export default {name:"ViewOffplanMilestone",components:{AddOffplanMilestone,EditOffplanMilestone},data(){return{items:[],loading:false,error:"",search:"",addOpen:false,editOpen:false,selectedId:null}},computed:{filtered(){const q=this.search.trim().toLowerCase();return q?this.items.filter(i=>[i.id,i.name,i.description,i.status,i.planned_date,i.actual_date,i.completion_percentage,this.relationLabel(i.offplan_property)].join(" ").toLowerCase().includes(q)):this.items},plannedCount(){return this.items.filter(i=>i.status==="planned").length},completedCount(){return this.items.filter(i=>i.status==="completed").length}},mounted(){this.load()},methods:{async load(){this.loading=true;this.error="";try{const res=await this.$apiGet("/get_offplan_milestones");const data=res?.data?.data||res?.data||res?.milestones||res;this.items=Array.isArray(data)?data:(Array.isArray(data?.results)?data.results:[])}catch(e){this.error=e?.message||"Unable to load milestones."}finally{this.loading=false}},openEdit(id){this.selectedId=id;this.editOpen=true},display(v){return String(v||"—").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase())},relationLabel(v){return v&&typeof v==="object"?(v.name||v.title||v.id||"—"):v??"—"}}};
</script>
<style scoped>.label{font-size:.75rem;font-weight:600;text-transform:uppercase;letter-spacing:.05em;color:#64748b}.big{margin-top:.25rem;font-size:1.5rem;font-weight:900;color:#0f172a}</style>
