<template>
<div class="min-h-full bg-slate-50 px-3 py-4 md:px-4 md:py-5"><div class="mx-auto max-w-[1600px]">
<header class="mb-4 flex flex-col gap-3 border-b border-slate-200 pb-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 class="text-lg font-semibold text-slate-900">Offplan milestones</h1><p class="mt-0.5 text-xs text-slate-500">Track project delivery dates and completion progress.</p></div><button @click="addOpen=true" class="inline-flex items-center justify-center gap-2 border border-primary bg-primary px-3 py-2 text-xs font-semibold text-white hover:opacity-90"><i class="fas fa-plus"></i> Add offplan milestone</button></header>
<section class="mb-3 grid border border-slate-200 bg-white sm:grid-cols-3"><div class="flex h-14 items-center justify-between border-b border-slate-200 px-3 sm:border-b-0 sm:border-r"><p class="text-[10px] font-medium uppercase tracking-wide text-slate-500">Total</p><p class="text-lg font-semibold leading-none text-slate-900">{{filtered.length}}</p></div><div class="flex h-14 items-center justify-between border-b border-slate-200 px-3 sm:border-b-0 sm:border-r"><p class="text-[10px] font-medium uppercase tracking-wide text-slate-500">Planned</p><p class="text-lg font-semibold leading-none text-slate-900">{{plannedCount}}</p></div><div class="flex h-14 items-center justify-between px-3"><p class="text-[10px] font-medium uppercase tracking-wide text-slate-500">Completed</p><p class="text-lg font-semibold leading-none text-slate-900">{{completedCount}}</p></div></section>
<section class="mb-3 border border-slate-200 bg-white"><div class="flex flex-col gap-2 p-3 lg:flex-row lg:items-center"><div class="relative flex-1"><i class="fas fa-search absolute left-2.5 top-1/2 -translate-y-1/2 text-xs text-slate-400"></i><input v-model="search" class="w-full border border-slate-300 bg-white py-1.5 pl-8 pr-2.5 text-xs text-slate-800 outline-none focus:border-primary" placeholder="Search milestone, property or status…"/></div><div class="flex items-center gap-2"><span class="text-[10px] text-slate-500">{{filtered.length}} result<span v-if="filtered.length!==1">s</span></span><button @click="load" class="border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"><i class="fas fa-rotate mr-1"></i>Refresh</button></div></div></section>
<section v-if="loading" class="border border-slate-200 bg-white p-8 text-center text-xs text-slate-500"><i class="fas fa-spinner fa-spin mr-2"></i>Loading milestones…</section><section v-else-if="error" class="border border-red-200 bg-red-50 p-4 text-xs text-red-700"><div class="flex items-center justify-between gap-3"><span>{{error}}</span><button @click="load" class="border border-red-300 bg-white px-2.5 py-1.5 text-[10px] font-semibold text-red-700">Retry</button></div></section><section v-else class="overflow-hidden border border-slate-200 bg-white">
<div v-if="!filtered.length" class="p-10 text-center"><div class="mb-2 text-primary"><i class="fas fa-flag-checkered text-xl"></i></div><h2 class="text-xs font-semibold text-slate-900">No offplan milestones found</h2><p class="mt-1 text-xs text-slate-500">Create a milestone or adjust your search criteria.</p></div>
<div v-else class="overflow-x-auto"><table class="min-w-[1050px] w-full border-collapse text-left"><thead class="bg-slate-50"><tr class="border-b border-slate-200"><th v-for="h in ['Milestone','Offplan property','Planned','Actual','Completion','Status','Actions']" :key="h" class="px-2 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-slate-500" :class="h==='Actions'?'text-right':''">{{h}}</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id" class="border-b border-slate-100 last:border-b-0 hover:bg-slate-50"><td class="px-2 py-1.5"><div class="text-xs font-medium leading-tight text-slate-900">{{item.name||('#'+item.id)}}</div><div class="mt-0.5 max-w-xs truncate text-[10px] text-slate-500">{{item.description||'No description'}}</div></td><td class="px-2 py-1.5 text-xs text-slate-700">{{relationLabel(item.offplan_property)}}</td><td class="px-2 py-1.5 text-xs text-slate-700">{{item.planned_date||'—'}}</td><td class="px-2 py-1.5 text-xs text-slate-700">{{item.actual_date||'—'}}</td><td class="px-2 py-1.5 text-xs font-semibold text-slate-900">{{item.completion_percentage??'—'}}</td><td class="px-2 py-1.5"><span class="inline-flex border border-primary/20 bg-primary/5 px-1.5 py-0.5 text-[10px] font-medium text-primary">{{display(item.status)}}</span></td><td class="px-2 py-1.5"><div class="flex justify-end gap-1"><router-link :to="{name:'OffplanMilestone-detail',params:{id:item.id}}" class="border border-slate-300 bg-white px-2 py-1 text-[10px] font-semibold text-slate-700 hover:border-primary hover:text-primary">View</router-link><button @click="openEdit(item.id)" class="border border-primary bg-primary px-2 py-1 text-[10px] font-semibold text-white hover:opacity-90">Edit</button></div></td></tr></tbody></table></div></section>
</div><AddOffplanMilestone :open="addOpen" @close="addOpen=false" @saved="load"/><EditOffplanMilestone :open="editOpen" :id="selectedId" @close="editOpen=false" @saved="load"/></div>
</template>
<script>
import AddOffplanMilestone from "./AddOffplanMilestone.vue";import EditOffplanMilestone from "./EditOffplanMilestone.vue";
export default {name:"ViewOffplanMilestone",components:{AddOffplanMilestone,EditOffplanMilestone},data(){return{items:[],loading:true,error:"",search:"",addOpen:false,editOpen:false,selectedId:null}},computed:{filtered(){const q=this.search.trim().toLowerCase();if(!q)return this.items;return this.items.filter(i=>[i.id,i.name,i.description,i.status,i.planned_date,i.actual_date,i.completion_percentage,this.relationLabel(i.offplan_property)].join(" ").toLowerCase().includes(q))},plannedCount(){return this.filtered.filter(i=>i.status==="planned").length},completedCount(){return this.filtered.filter(i=>i.status==="completed").length}},mounted(){this.load()},methods:{async load(){this.loading=true;this.error="";try{this.items=await this.$getOffplanMilestones()}catch(e){this.error=e?.message||"Unable to load milestones."}finally{this.loading=false}},openEdit(id){this.selectedId=id;this.editOpen=true},display(v){if(v===null||v===undefined||v==="")return"—";return String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())},relationLabel(v){return v&&typeof v==="object"?(v.name||v.title||v.developer||v.project_name||v.id||"—"):(v??"—")}}};
</script>